### ISSUE TITLE
Add callbacks to use instead of method overrides

### ISSUE THREAD

**Issue by tchaloupka** [chalucha/mqtt-d#23]
Keep the methods not final to keep API compatibility.
Add the way to attach callback functions to provided events.

**Comment by crimaniak** [comment]
BTW, now I have ugly connect1() and disconnect1() methods because I need to do additional things on it, but connect() and disconnect() are final.

**Comment by tchaloupka** [comment]
I've added the callbacks to the settings. That can be used instead of method overrides (I'll probably make them obsolete in v0.3.0).

But I don't understand your point, that is exactly the meaning of callbacks (or onConnAck/onDisconnect methods override) to make something additional during connection or disconnection.
Isn't that enough?

**Comment by crimaniak** [comment]
Sometimes you need to do something before base action, sometimes - after, sometimes before and after, as in my case. Callbacks approach is limited because you need to implement callback on every usage case. So both inheritance and composition approaches are better for complex cases.
