### ISSUE TITLE
MQTT Received PUBCOMP with unknown ID - PubComp(XXX, YYY)

### ISSUE THREAD

**Issue by deviator** [chalucha/mqtt-d#27]
Some time after the start of my programs I have messages like this
```
MQTT Received PUBCOMP with unknown ID - PubComp(XXX, YYY)
```
and
```
1497350637: Warning: Received PUBREL from One.pub for an unknown packet identifier XXX.
```
from `mosquitto 1.4.11`.
It's greatly slows down message dispatching to 3-5 minutes per message.
It's for QoS2, without QoS2 messages are lose.

here source code
https://github.com/deviator/drmi/tree/master/source/drmi/ps
https://github.com/deviator/drmi/tree/master/example/mqtt

**Comment by tchaloupka** [comment]
Thanks for the report. I've not tested QoS2 thoroughly because we are forced to use RabbitMQ. It seems that PUBREL is sent with wrong id.

**Comment by tchaloupka** [comment]
Please try to retest this with v0.2.0-alpha.6
With the last fix the provided tests behave much better and I didn't hit the described error.

If you find the problem again, please try to provide logs for Mosquito and the test app with trace log and version MqttDebug enabled, so we can see what was sent and received exactly.

**Comment by deviator** [comment]
On alpha.6 I don't hit this error, I think it's solved, thank you!
