### ISSUE TITLE
Client Identifier SHOULD be 1 to 23 characters long

### ISSUE THREAD

**Issue by deviator** [chalucha/mqtt-d#28]
why? clients in other languages can set client id more what 23 chars, for example paho.mqtt (python) registered as `a7868812-de35-4ca7-bf54-40ad0dd2e2b8` (36 chars)

**Comment by tchaloupka** [comment]
I've lessen the requirements.
The limit is described here: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349242
but it is just a soft limit.

Most brokers probably supports this, so this should be ok..
